#pragma once

#include "Utils/ByteSearch.h"

// Byte-pattern signatures for OpenSteamTool hooks against
// steamclient64.dll and steamui.dll. Auto-generated by
// steam-monitor; manual edits will be overwritten on the next cycle.
//
// Each Sigs[] array is keyed by Steam manifest build id (the digit
// string returned by steam.exe!GetBootstrapperVersion at runtime).
// The trailing channel comment records which channel that build was
// on at write time — used by the bot to apply per-channel history
// caps on the next regeneration.
//
// `??` is the wildcard byte.


/* -------------------------------------------------------------------------- */
/*                                SteamClient                                 */
/* -------------------------------------------------------------------------- */

inline const Signature BBuildAndAsyncSendFrameSigs[] = {
    {"1778803745", "48 8B C4 55 48 8D 68 A1 48 81 EC C0 00 00 00 48 89 70 18"},  // beta
    {"1779486452", "48 8B C4 55 48 8D 68 A1 48 81 EC C0 00 00 00"},  // new stable
    {"1778281814", "48 8B C4 55 48 8D 68 A1 48 81 EC C0 00 00 00"},  // stable
};

inline const Signature BuildDepotDependencySigs[] = {
    {"1778803745", "48 8B C4 4C 89 48 20 89 50 10 48 89 48 08 55 ?? 48 8D"},  // beta
    {"1779486452", "48 8B C4 4C 89 48 20 89 50 10 48 89 48 08 55 ?? 48 8D"},  // new stable
    {"1778281814", "48 8B C4 4C 89 48 20 89 50 10 48 89 48 08 55 ?? 48 8D"},  // stable
};

inline const Signature BuildSpawnEnvBlockSigs[] = {
    {"1779155395", "4C 89 4C 24 ?? 4C 89 44 24 ?? 48 89 54 24 ?? 48 89 4C 24 ?? 55 53 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 ?? ?? ?? ?? 48 81 EC ?? ?? ?? ?? 48 8B 05"},  // beta
    {"1779486452", "48 89 5C 24 ?? 4C 89 44 24 ?? 48 89 54 24 ?? 48 89 4C 24 ?? 55 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 ?? ?? ?? ?? 48 81 EC ?? ?? ?? ?? 48 8B 05"},  // new stable
    {"1778281814", "48 89 5C 24 ?? 4C 89 44 24 ?? 48 89 54 24 ?? 48 89 4C 24 ?? 55 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 ?? ?? ?? ?? 48 81 EC ?? ?? ?? ?? 48 8B 05"},  // stable
};

inline const Signature CUtlBufferEnsureCapacitySigs[] = {
    {"1778803745", "48 89 5C 24 08 57 48 83 EC 30 48 8B D9 8D"},  // beta
    {"1779486452", "48 89 5C 24 ?? 57 48 83 EC ?? 0F B6 41 ?? 8D 7A"},  // new stable
    {"1778281814", "48 89 5C 24 ?? 57 48 83 EC ?? 0F B6 41 ?? 8D 7A"},  // stable
};

inline const Signature CUtlMemoryGrowSigs[] = {
    {"1778803745", "48 89 5C 24 10 57 48 83 EC 30 8B FA 48 8B D9 8B 51 08"},  // beta
    {"1779486452", "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 30"},  // new stable
    {"1778281814", "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 30"},  // stable
};

inline const Signature CheckAppOwnershipSigs[] = {
    {"1778803745", "48 8B C4 89 50 10 48 89 48 08 55 53"},  // beta
    {"1779486452", "48 8B C4 89 50 10 55 53 48 8D 68 D8"},  // new stable
    {"1778281814", "48 8B C4 89 50 10 55 53 48 8D 68 D8"},  // stable
};

inline const Signature GetAppDataFromAppInfoSigs[] = {
    {"1778803745", "40 53 55 56 57 41 56 41 57 48 81 EC 78 01 00 00 41 C6 01 00"},  // beta
    {"1779486452", "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 81 EC 70 01 00 00"},  // new stable
    {"1778281814", "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 81 EC 70 01 00 00"},  // stable
};

inline const Signature GetAppIDForCurrentPipeSigs[] = {
    {"1778803745", "8B 81 30 0D 00 00 83 F8"},  // beta
    {"1779486452", "48 83 EC 08 8B 81 30 0D 00 00 4C 8B D9 44 8B 91 D8 00 00 00 83 F8 FF"},  // new stable
    {"1778281814", "48 83 EC 08 8B 81 30 0D 00 00 4C 8B D9 44 8B 91 D8 00 00 00 83 F8 FF"},  // stable
};

inline const Signature GetPackageInfoSigs[] = {
    {"1778803745", "48 89 5C 24 18 89 54 24 10 55 56 57 48 83 EC 20 44 8B 49 20"},  // beta
    {"1779486452", "48 89 6C 24 ?? 41 56 48 83 EC ?? 8B 41 ?? 49 8B E8"},  // new stable
    {"1778281814", "48 89 6C 24 ?? 41 56 48 83 EC ?? 8B 41 ?? 49 8B E8"},  // stable
};

inline const Signature GetPipeClientSigs[] = {
    {"1778803745", "85 D2 74 ?? 44 0F B7 CA"},  // beta
    {"1779486452", "85 D2 74 ?? 44 0F B7 CA"},  // new stable
    {"1778281814", "85 D2 74 ?? 44 0F B7 CA"},  // stable
};

inline const Signature IPCProcessMessageSigs[] = {
    {"1778803745", "48 89 5C 24 18 48 89 6C 24 20 57 41 54 41 55 41 56 41 57 48"},  // beta
    {"1779486452", "48 89 5C 24 ?? 48 89 6C 24 ?? 56 41 54 41 55 41 56 41 57 48 83 EC ?? 49 8B D9"},  // new stable
    {"1778281814", "48 89 5C 24 ?? 48 89 6C 24 ?? 56 41 54 41 55 41 56 41 57 48 83 EC ?? 49 8B D9"},  // stable
};

inline const Signature KeyValues_FindOrCreateKeySigs[] = {
    {"1778803745", "48 2B D1 F6 C1 07 74 14"},  // beta
    {"1779486452", "48 8B C4 4C 89 48 20 57 48 81 EC 60 04 00 00 48 89 70 E8 48 8B FA"},  // new stable
    {"1778281814", "48 8B C4 4C 89 48 20 57 48 81 EC 60 04 00 00 48 89 70 E8 48 8B FA"},  // stable
};

inline const Signature KeyValues_ReadAsBinarySigs[] = {
    {"1778803745", "48 8B C4 44 88 48 20 55"},  // beta
    {"1779486452", "48 8B C4 44 88 48 20 44 89 40 18 55 57 48 8D 68 A9 48 81 EC B8 00 00 00"},  // new stable
    {"1778281814", "48 8B C4 44 88 48 20 44 89 40 18 55 57 48 8D 68 A9 48 81 EC B8 00 00 00"},  // stable
};

inline const Signature LoadDepotDecryptionKeySigs[] = {
    {"1778803745", "40 53 55 56 57 48 83 EC 38 48 63 FA 49 8B E9"},  // beta
    {"1779486452", "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 30 48 63 FA 49 8B E9 8B D7 49 8B D8 48 8B F1"},  // new stable
    {"1778281814", "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 30 48 63 FA 49 8B E9 8B D7 49 8B D8 48 8B F1"},  // stable
};

inline const Signature LoadPackageSigs[] = {
    {"1778803745", "44 89 44 24 18 53 55 56 57 41 55"},  // beta
    {"1779486452", "48 89 5C 24 18 48 89 6C 24 20 56 57 41 54 41 55 41 57 48 81 EC 20 01"},  // new stable
    {"1778281814", "48 89 5C 24 18 48 89 6C 24 20 56 57 41 54 41 55 41 57 48 81 EC 20 01"},  // stable
};

inline const Signature MarkLicenseAsChangedSigs[] = {
    {"1778803745", "48 89 5C 24 20 89 54 24 10 55 56 57 48 83 EC 20"},  // beta
    {"1779486452", "89 54 24 ?? 53 55 56 57 41 56 48 83 EC"},  // new stable
    {"1778281814", "89 54 24 ?? 53 55 56 57 41 56 48 83 EC"},  // stable
};

inline const Signature OptedInMaskSigs[] = {
    {"1779155395", "89 54 24 ?? 55 53 56 57 41 54 41 55 48 8D AC 24"},  // beta
    {"1779486452", "89 54 24 ?? 55 53 56 41 55 41 56 41 57"},  // new stable
    {"1778281814", "89 54 24 ?? 55 53 56 41 55 41 56 41 57"},  // stable
};

inline const Signature PchMsgNameFromEMsgSigs[] = {
    {"1778803745", "48 89 5C 24 08 57 48 83 EC 20 8B D9 E8"},  // beta
    {"1779486452", "48 89 5C 24 08 57 48 83 EC 20 8B D9 E8"},  // new stable
    {"1778281814", "48 89 5C 24 08 57 48 83 EC 20 8B D9 E8"},  // stable
};

inline const Signature ProcessPendingLicenseUpdatesSigs[] = {
    {"1778803745", "41 56 41 57 48 83 EC 38 83"},  // beta
    {"1779486452", "4C 8B DC 49 89 4B 08 41 55 41 57 48 83 EC 48 4C 8B E9"},  // new stable
    {"1778281814", "4C 8B DC 49 89 4B 08 41 55 41 57 48 83 EC 48 4C 8B E9"},  // stable
};

inline const Signature RecvPktSigs[] = {
    {"1778803745", "48 8B C4 55 48 8D A8 98 F6 FF FF 48 81 EC 60 0A"},  // beta
    {"1779486452", "48 8B C4 55 48 8D A8 98 F6 FF FF 48 81 EC 60 0A"},  // new stable
    {"1778281814", "48 8B C4 55 48 8D A8 98 F6 FF FF 48 81 EC 60 0A"},  // stable
};

inline const Signature SendCallbackToPipeSigs[] = {
    {"1778803745", "48 89 5C 24 ?? 57 48 83 EC ?? 41 8B D9 41 8B F8 E8 ?? ?? ?? ?? 48 8B C8"},  // beta
    {"1779486452", "48 89 5C 24 ?? 57 48 83 EC ?? 41 8B D9 41 8B F8 E8 ?? ?? ?? ?? 48 8B C8"},  // new stable
    {"1778281814", "48 89 5C 24 ?? 57 48 83 EC ?? 41 8B D9 41 8B F8 E8 ?? ?? ?? ?? 48 8B C8"},  // stable
};

inline const Signature SpawnProcessSigs[] = {
    {"1778803745", "48 89 5C 24 18 4C 89 4C 24 20 48 89 54 24 10 55 56 57 41 54 41 55 41 56 41 57 48 8D"},  // beta
    {"1779486452", "48 89 5C 24 18 4C 89 4C 24 20 48 89 54 24 10 55 56 57 41 54 41 55 41 56 41 57 48 8D"},  // new stable
    {"1778281814", "48 89 5C 24 18 4C 89 4C 24 20 48 89 54 24 10 55 56 57 41 54 41 55 41 56 41 57 48 8D"},  // stable
};

/* -------------------------------------------------------------------------- */
/*                                  SteamUI                                   */
/* -------------------------------------------------------------------------- */

inline const Signature GetAppByIDSigs[] = {
    {"1779155395", "89 54 24 ?? 53 48 83 EC ?? 48 8B 05 ?? ?? ?? ?? 41 0F B6 D8"},  // beta
    {"1779486452", "89 54 24 ?? 56 48 83 EC ?? 48 8B 05"},  // new stable
    {"1778281814", "89 54 24 ?? 56 48 83 EC ?? 48 8B 05"},  // stable
};

inline const Signature LoadModuleWithPathSigs[] = {
    {"1778803745", "48 89 5C 24 18 55 56 41 57 48 83 EC 40"},  // beta
    {"1779486452", "48 89 5C 24 18 48 89 6C 24 20 56 41 54 41 57 48 83 EC 40"},  // new stable
    {"1778281814", "48 89 5C 24 18 48 89 6C 24 20 56 41 54 41 57 48 83 EC 40"},  // stable
};

inline const Signature TopManagerCallSigs[] = {
    {"1779155395", "83 FE 07 0F 84 ?? ?? ?? ?? E8 ?? ?? ?? ?? 45 33 C0"},  // beta
    {"1779486452", "83 FF 07 0F 84 ?? ?? ?? ?? E8 ?? ?? ?? ?? 45 33 C0"},  // new stable
    {"1778281814", "83 FF 07 0F 84 ?? ?? ?? ?? E8 ?? ?? ?? ?? 45 33 C0"},  // stable
};

inline const Signature AddProtobufAsBinarySigs[] = {
    {"1779155395", "40 53 55 56 57 48 83 EC ?? 48 8B 05 ?? ?? ?? ?? 48 8B F2"},  // beta
    {"1779486452", "48 89 5C 24 ?? 48 89 6C 24 ?? 48 89 74 24 ?? 57 48 83 EC 20 48 8B 05 ?? ?? ?? ?? 48 8B F2 48 8B D9 44 8B 00"},  // new stable
    {"1778281814", "48 89 5C 24 ?? 48 89 6C 24 ?? 48 89 74 24 ?? 57 48 83 EC 20 48 8B 05 ?? ?? ?? ?? 48 8B F2 48 8B D9 44 8B 00"},  // stable
};
